apiVersion: v1
kind: Service
metadata:
  name: cacheservice
spec:
  ports:
    - name: "redisport"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: cache
status:
  loadBalancer: {}
