apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ctfd
spec:
  wildcardPolicy: None
  port:
    targetPort: webport
  tls:
    termination: edge
  to:
    kind: Service
    name: nginxservice
    weight: 100
