apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ctfd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Helm
        io.kompose.service: ctfd
    spec:
      containers:
        - env:
            - name: ACCESS_LOG
              value: '-'
            - name: DATABASE_URL
              value: mysql+pymysql://{{ .Values.dbService.user }}:{{ .Values.dbService.password }}@dbservice/{{ .Values.dbService.database }}
            - name: ERROR_LOG
              value: '-'
            - name: LOG_FOLDER
              value: /var/log/CTFd
            - name: REDIS_URL
              value: redis://cacheservice:6379
            - name: REVERSE_PROXY
              value: "true"
            - name: UPLOAD_FOLDER
              value: /var/uploads
            - name: WORKERS
              value: "1"
          image: ctfd/ctfd
          name: ctfd
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
