apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --wait_timeout=28800
            - --log-warnings=0
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.dbService.database }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.dbService.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.dbService.rootPassword }}
            - name: MYSQL_USER
              value: {{ .Values.dbService.user }}
          image: mariadb:10.4.12
          name: db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-claim0
          ports:
            - containerPort: 3306
      restartPolicy: Always
      volumes:
        - name: db-claim0
status: {}
