apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: dbservice
spec:
  ports:
    - name: "mysql"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
