apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ctfd
  name: nginxservice
spec:
  ports:
    - name: "webport"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
