apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
         io.kompose.network/ctfd-internal: "true"
         io.kompose.service: cache
    spec:
      containers:
        - image: redis:4
          name: cache
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: cache-claim0
      restartPolicy: Always
      volumes:
        - name: cache-claim0
          persistentVolumeClaim:
            claimName: cache-claim0
status: {}