apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
spec:
  host: ctfd.apps.aro-pisanonprod.euw-hub02.azure.volvo.net
  wildcardPolicy: None
  port:
    targetPort: 80
  tls:
    termination: edge
  to:
    kind: Service
    name: nginxservice
    weight: 100
