apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - image: bitnami/nginx
          name: nginx
          ports:
            - containerPort: 8080
          volumeMounts:
           - name: nginx-conf
             mountPath: /opt/bitnami/nginx/conf/nginx.conf
             subPath: nginx.conf
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
status: {}
