apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ctfd
    app.kubernetes.io/managed-by: Helm
  name: nginxservice
spec:
  ports:
    - name: "webport"
      port: 80
      targetPort: 8081
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
